# Linux setup required
dist: trusty
sudo: required

# This is a Rust build
language: rust
cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

# Will need access to the Docker service to run "cross"
services: docker

env:
  global:
    - ARTIFACT=httpbox

matrix:
  include:
    # ------------------------------------ Stable channel builds
    # Linux 32 and 64 bit
    - env: RUST_BUILD_TOOL=cross  RUST_TARGET=i686-unknown-linux-gnu    PKG=httpbox-i686-linux-gnu.tgz
      rust: stable
#    - env: RUST_TARGET=i686-unknown-linux-musl
#      rust: stable
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=x86_64-unknown-linux-gnu  PKG=httpbox-x86_64-linux-gnu.tgz
      rust: stable
#    - env: RUST_TARGET=x86_64-unknown-linux-musl
#      rust: stable
    # Mac OS X 32 and 64 bit
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=i686-apple-darwin         PKG=httpbox-i686-macosx.tgz
      os: osx
      rust: stable
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=x86_64-apple-darwin       PKG=httpbox-x86_64-macosx.tgz
      os: osx
      rust: stable
    # Windows 32 and 64 bit
    - env: RUST_BUILD_TOOL=cross  RUST_TARGET=i686-pc-windows-gnu       PKG=httpbox-i686-windows.tgz      ARTIFACT=httpbox.exe
      rust: stable
    - env: RUST_BUILD_TOOL=cross  RUST_TARGET=x86_64-pc-windows-gnu     PKG=httpbox-x86_64-windows.tgz    ARTIFACT=httpbox.exe
      rust: stable
    # ------------------------------------ Beta channel builds
    # Beta builds
    - env: RUST_BUILD_TOOL=cross  RUST_TARGET=i686-unknown-linux-gnu
      rust: beta
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=x86_64-apple-darwin
      os: osx
      rust: beta

install: |
  ./.travis.scripts/setup.sh

script: |
  ./.travis.scripts/build.sh
