# Linux setup required
dist: trusty
sudo: required

# This is a Rust build
language: rust
cache: cargo

# Will need access to the Docker service to run "cross"
services: docker

env:
  global:
    - ARTIFACT=httpbox  #< By default, artifact is named 'httpbox', same as defined in 'Cargo.toml'
    - RELEASE_PKG=none  #< By default, nothing gets released

matrix:
  include:
    # ------------------------------------ Stable channel builds
    # Linux 32 and 64 bit
    - env: RUST_BUILD_TOOL=cross  RUST_TARGET=i686-unknown-linux-gnu    RELEASE_PKG=httpbox-i686-linux-gnu.tgz
      rust: stable
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=x86_64-unknown-linux-gnu  RELEASE_PKG=httpbox-x86_64-linux-gnu.tgz
      rust: stable
    # Mac OS X 32 and 64 bit
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=i686-apple-darwin         RELEASE_PKG=httpbox-i686-macosx.tgz
      os: osx
      rust: stable
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=x86_64-apple-darwin       RELEASE_PKG=httpbox-x86_64-macosx.tgz
      os: osx
      rust: stable
    # Windows 32 and 64 bit
    - env: RUST_BUILD_TOOL=cross  RUST_TARGET=i686-pc-windows-gnu       RELEASE_PKG=httpbox-i686-windows.tgz      ARTIFACT=httpbox.exe
      rust: stable
    - env: RUST_BUILD_TOOL=cross  RUST_TARGET=x86_64-pc-windows-gnu     RELEASE_PKG=httpbox-x86_64-windows.tgz    ARTIFACT=httpbox.exe
      rust: stable
    # ------------------------------------ Beta channel builds
    # Beta builds
    - env: RUST_BUILD_TOOL=cross  RUST_TARGET=i686-unknown-linux-gnu
      rust: beta
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: RUST_BUILD_TOOL=cargo  RUST_TARGET=x86_64-apple-darwin
      os: osx
      rust: beta

install: |
  ./.travis.scripts/setup.sh

script: |
  ./.travis.scripts/build.sh
